name: "sambamba_slice"
description: Tools for working with SAM/BAM data
keywords:
  - sambamba
  - slice
tools:
  - "sambamba":
      description: "Tools for working with SAM/BAM data."
      homepage: "https://lomereiter.github.io/sambamba/"
      documentation: "https://lomereiter.github.io/sambamba/"
      tool_dev_url: "https://lomereiter.github.io/sambamba/"
      doi: ""
      licence: "['GPL v2']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [subject_name: 'subject', ['sample_name', 'tumor']: 'sample', ['tumor', 'bam']: 'path/to/bam'

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [subject_name: 'subject', ['sample_name', 'tumor']: 'sample', ['tumor', 'bam']: 'path/to/bam'
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@scwatts"
