name: "PURPLE_germline"
description: PURPLE is a purity ploidy estimator for whole genome sequenced data
keywords:
  - purple
  - variant caller
  - ploidy
  - purity
  - cnv
  - sv
tools:
  - "PURPLE":
      description: "PURPLE is a purity ploidy estimator for whole genome sequenced data."
      homepage: "https://github.com/hartwigmedical/hmftools/tree/master/purple"
      documentation: "https://github.com/hartwigmedical/hmftools/tree/master/purple"
      tool_dev_url: "https://github.com/hartwigmedical/hmftools/tree/master/purple"
      doi: ""
      licence: "['GPL v3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [subject_name: 'subject', ['sample_name', 'tumor']: 'sample', ['tumor', 'bam']: 'path/to/bam'
  - amber:
      type: directory
      description: AMBER output directory
  - cobalt:
      type: directory
      description: COBALT output directory
  - sv_soft_vcf:
      type: file
      description: GRIPSS soft filtered VCF file
      pattern: "*.{vcf.gz}"
  - sv_soft_vcf_index:
      type: file
      description: GRIPSS soft filtered VCF index file
      pattern: "*.{vcf.gz.tbi}"
  - sv_hard_vcf:
      type: file
      description: GRIPSS hard filtered VCF file
      pattern: "*.{vcf.gz}"
  - sv_hard_vcf_index:
      type: file
      description: GRIPSS hard filtered VCF index file
      pattern: "*.{vcf.gz.tbi}"
  - smlv_tumor_vcf:
      type: file
      description: Input small variant tumor VCF file
      pattern: "*.{vcf.gz}"
  - smlv_normal_vcf:
      type: file
      description: Input small variant normal VCF file
      pattern: "*.{vcf.gz}"
  - ref_data_genome_dir:
      type: directory
      description: Directory containing reference genome
  - ref_data_genome_fn:
      type: string
      description: Reference genome filename
  - gc_profile:
      type: file
      description: COBALT GC Profile file
      pattern: "*.{cnp}"
  - known_hotspots:
      type: file
      description: HMF Known Hotspots file
      pattern: "*.{vcf.gz}"
  - driver_gene_panel:
      type: file
      description: HMF Driver Gene Panel file
      pattern: "*.{csv}"
  - ensembl_data_dir:
      type: directory
      description: HMF Ensembl Data Cache directory


output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [subject_name: 'subject', ['sample_name', 'tumor']: 'sample', ['tumor', 'bam']: 'path/to/bam'
  - purple_dir:
      type: directory
      description: PURPLE output directory
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@scwatts"
