name: "PAVE_somatic"
description: PAVE annotates a somatic variant VCF with gene and transcript coding and protein effects
keywords:
  - pave
  - annotation
  - gene
  - transcript
  - protein
  - vcf
tools:
  - "PAVE":
      description: "PAVE annotates a somatic variant VCF with gene and transcript coding and protein effects."
      homepage: "https://github.com/hartwigmedical/hmftools/tree/master/pave"
      documentation: "https://github.com/hartwigmedical/hmftools/tree/master/pave"
      tool_dev_url: "https://github.com/hartwigmedical/hmftools/tree/master/pave"
      doi: ""
      licence: "['GPL v3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [subject_name: 'subject', ['sample_name', 'tumor']: 'sample', ['tumor', 'bam']: 'path/to/bam'

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [subject_name: 'subject', ['sample_name', 'tumor']: 'sample', ['tumor', 'bam']: 'path/to/bam'
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@scwatts"
