name: "COBALT"
description: Count bam lines determines the read depth ratios of the supplied tumor and reference genomes
keywords:
  - cobalt
  - read depth ratios
  - cnv
tools:
  - "COBALT":
      description: "Count bam lines determines the read depth ratios of the supplied tumor and reference genomes."
      homepage: "https://github.com/hartwigmedical/hmftools/tree/master/cobalt"
      documentation: "https://github.com/hartwigmedical/hmftools/tree/master/cobalt"
      tool_dev_url: "https://github.com/hartwigmedical/hmftools/tree/master/cobalt"
      doi: ""
      licence: "['GPL v3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [subject_name: 'subject', ['sample_name', 'tumor']: 'sample', ['tumor', 'bam']: 'path/to/bam'
  - tumor_bam:
      type: file
      description: BAM file
      pattern: "*.{bam}"
  - normal_bam:
      type: file
      description: BAM file
      pattern: "*.{bam}"
  - tumor_bai:
      type: file
      description: BAI file
      pattern: "*.{bai}"
  - normal_bai:
      type: file
      description: BAI file
      pattern: "*.{bai}"
  - gc_profile:
      type: file
      description: COBALT GC Profile file
      pattern: "*.{cnp}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [subject_name: 'subject', ['sample_name', 'tumor']: 'sample', ['tumor', 'bam']: 'path/to/bam'
  - cobalt:
      type: directory
      description: COBALT output directory
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@scwatts"
