name: "LILAC"
description: LILAC is a WGS tool for HLA typing and somatic CNV and SNV calling
keywords:
  - lilac
tools:
  - "LILAC":
      description: "LILAC is a WGS tool for HLA typing and somatic CNV and SNV calling."
      homepage: "https://github.com/hartwigmedical/hmftools/tree/master/lilac"
      documentation: "https://github.com/hartwigmedical/hmftools/tree/master/lilac"
      tool_dev_url: "https://github.com/hartwigmedical/hmftools/tree/master/lilac"
      doi: ""
      licence: "['GPL v3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [subject_name: 'subject', ['sample_name', 'tumor']: 'sample', ['tumor', 'bam']: 'path/to/bam'

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [subject_name: 'subject', ['sample_name', 'tumor']: 'sample', ['tumor', 'bam']: 'path/to/bam'
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@scwatts"
