name: "ASSEMBLE"
description: Assemble SVs with GRIDSS
keywords:
  - gridss
  - assemble
  - sv
tools:
  - "gridss":
      description: "GRIDSS is a module software suite containing tools useful for the detection of genomic rearrangements."
      homepage: "https://github.com/PapenfussLab/gridss"
      documentation: "https://github.com/PapenfussLab/gridss"
      tool_dev_url: "https://github.com/PapenfussLab/gridss"
      doi: ""
      licence: "['GPL >=3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [subject_name: 'subject', ['sample_name', 'tumor']: 'sample', ['tumor', 'bam']: 'path/to/bam'
  - tumor_bam:
      type: file
      description: BAM file
      pattern: "*.{bam}"
  - normal_bam:
      type: file
      description: BAM file
      pattern: "*.{bam}"
  - tumor_preprocess:
      type: directory
      description: GRIDSS preprocess output directory (tumor)
  - normal_preprocess:
      type: directory
      description: GRIDSS preprocess output directory (normal)
  - ref_data_genome_dir:
      type: directory
      description: Directory containing reference genome
  - ref_data_genome_fn:
      type: string
      description: Reference genome filename
  - blacklist:
      type: file
      description: GRIDSS blacklist file
      pattern: "*.{bed}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [subject_name: 'subject', ['sample_name', 'tumor']: 'sample', ['tumor', 'bam']: 'path/to/bam'
  - assembly_dir:
      type: directory
      description: GRIDSS assemble output directory
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@scwatts"
